services:
  # 1. Eureka Server
  - type: web
    name: eureka-server
    env: docker
    plan: free
    region: oregon
    rootDir: ./eureka-server # <-- Corregido a rootDir

  # 2. Microservicio de Pedidos
  - type: web
    name: mi-microservicio-pedido
    env: docker
    plan: free
    region: oregon
    rootDir: ./microservicio-pedido # <-- Corregido a rootDir
    envVars:
      - key: PORT
        value: 8083
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: ${eureka_server_url}/eureka/

  # 3. API Gateway
  - type: web
    name: api-gateway
    env: docker
    plan: free
    region: oregon
    rootDir: ./api-gateway # <-- Corregido a rootDir
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: ${eureka_server_url}/eureka/