databases:
  - name: db-404store
    databaseName: db_404store
    user: admin_404store
    plan: free
    region: oregon

services:
  - type: web
    name: eureka-server
    env: docker
    plan: free
    region: oregon
    rootDir: ./eureka-server

  - type: web
    name: microservicio-cliente
    env: docker
    plan: free
    region: oregon
    rootDir: ./cliente
    envVars:
      - key: PORT
        value: 8081
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: https://eureka-server-mg8f.onrender.com/eureka/
      - key: DB_URL
        value: jdbc:postgresql://dpg-d96npf8js32c7399us90-a:5432/db_404store
      - key: DB_USER
        fromDatabase:
          name: db-404store
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: db-404store
          property: password

  - type: web
    name: microservicio-producto
    env: docker
    plan: free
    region: oregon
    rootDir: ./producto
    envVars:
      - key: PORT
        value: 8082
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: https://eureka-server-mg8f.onrender.com/eureka/
      - key: DB_URL
        value: jdbc:postgresql://dpg-d96npf8js32c7399us90-a:5432/db_404store
      - key: DB_USER
        fromDatabase:
          name: db-404store
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: db-404store
          property: password

  - type: web
    name: microservicio-pedido
    env: docker
    plan: free
    region: oregon
    rootDir: ./pedido
    envVars:
      - key: PORT
        value: 8083
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: https://eureka-server-mg8f.onrender.com/eureka/
      - key: DB_URL
        value: jdbc:postgresql://dpg-d96npf8js32c7399us90-a:5432/db_404store
      - key: DB_USER
        fromDatabase:
          name: db-404store
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: db-404store
          property: password

  - type: web
    name: microservicio-pago
    env: docker
    plan: free
    region: oregon
    rootDir: ./pago
    envVars:
      - key: PORT
        value: 8084
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: https://eureka-server-mg8f.onrender.com/eureka/
      - key: DB_URL
        value: jdbc:postgresql://dpg-d96npf8js32c7399us90-a:5432/db_404store
      - key: DB_USER
        fromDatabase:
          name: db-404store
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: db-404store
          property: password

  - type: web
    name: microservicio-envio
    env: docker
    plan: free
    region: oregon
    rootDir: ./envio
    envVars:
      - key: PORT
        value: 8085
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: https://eureka-server-mg8f.onrender.com/eureka/
      - key: DB_URL
        value: jdbc:postgresql://dpg-d96npf8js32c7399us90-a:5432/db_404store
      - key: DB_USER
        fromDatabase:
          name: db-404store
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: db-404store
          property: password

  - type: web
    name: microservicio-notificacion
    env: docker
    plan: free
    region: oregon
    rootDir: ./notificacion
    envVars:
      - key: PORT
        value: 8086
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: https://eureka-server-mg8f.onrender.com/eureka/
      - key: DB_URL
        value: jdbc:postgresql://dpg-d96npf8js32c7399us90-a:5432/db_404store
      - key: DB_USER
        fromDatabase:
          name: db-404store
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: db-404store
          property: password

  - type: web
    name: microservicio-promocion
    env: docker
    plan: free
    region: oregon
    rootDir: ./promocion
    envVars:
      - key: PORT
        value: 8087
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: https://eureka-server-mg8f.onrender.com/eureka/
      - key: DB_URL
        value: jdbc:postgresql://dpg-d96npf8js32c7399us90-a:5432/db_404store
      - key: DB_USER
        fromDatabase:
          name: db-404store
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: db-404store
          property: password

  - type: web
    name: microservicio-inventario
    env: docker
    plan: free
    region: oregon
    rootDir: ./inventario
    envVars:
      - key: PORT
        value: 8088
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: https://eureka-server-mg8f.onrender.com/eureka/
      - key: DB_URL
        value: jdbc:postgresql://dpg-d96npf8js32c7399us90-a:5432/db_404store
      - key: DB_USER
        fromDatabase:
          name: db-404store
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: db-404store
          property: password

  - type: web
    name: microservicio-resena
    env: docker
    plan: free
    region: oregon
    rootDir: ./resena
    envVars:
      - key: PORT
        value: 8089
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: https://eureka-server-mg8f.onrender.com/eureka/
      - key: DB_URL
        value: jdbc:postgresql://dpg-d96npf8js32c7399us90-a:5432/db_404store
      - key: DB_USER
        fromDatabase:
          name: db-404store
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: db-404store
          property: password

  - type: web
    name: microservicio-devolucion
    env: docker
    plan: free
    region: oregon
    rootDir: ./devolucion
    envVars:
      - key: PORT
        value: 8090
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: https://eureka-server-mg8f.onrender.com/eureka/
      - key: DB_URL
        value: jdbc:postgresql://dpg-d96npf8js32c7399us90-a:5432/db_404store
      - key: DB_USER
        fromDatabase:
          name: db-404store
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: db-404store
          property: password

  - type: web
    name: api-gateway
    env: docker
    plan: free
    region: oregon
    rootDir: ./api-gateway
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: https://eureka-server-mg8f.onrender.com/eureka/