server:
  port: ${PORT}

spring:
  application:
    name: microservicio-producto
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
    fetch-registry: false
    register-with-eureka: true
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 5
  instance:
    preferIpAddress: true