server:
  port: 8081

spring:
  application:
    name: microservicio-cliente
  datasource:
    url: jdbc:mysql://mysql-db:3306/db_404store?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

app:
  jwt:
    secret: clave-secreta-jwt-duoc-2026-demo-123456
    expiration-ms: 3600000